Invoice_System/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('panel.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panel/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add_client/', views.add_client, name='add_client'),
    path('add_product/', views.add_product, name='add_product'),
    path('add_invoice/', views.add_invoice, name='add_invoice'),
    path('success/', views.success, name='success'),
    path('get_invoice_print/', views.get_invoice_print, name='get_invoice_print')
]

panel/models.py
import datetime
from django.core.validators import MinValueValidator
from django.db import models
from decimal import Decimal


# Create your models here.

class Client(models.Model):
    """Client instance"""
    class Meta:
        managed = True

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=80)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    postcode = models.CharField(max_length=10)
    country = models.CharField(max_length=255)
    nip = models.CharField(max_length=20)

    @property
    def full_name(self):
        """Returns the person's full name.

        Returns
        -------
        str
            string containing person's full name
        """
        return f'{self.first_name} {self.last_name}'

    @property
    def full_address(self):
        """Get full address of client

        Returns
        -------
        str
            string containing full address of client
        """
        return f'{self.address}, {self.postcode} {self.city}, {self.country}'

    def __str__(self):
        return self.full_name


class Product(models.Model):
    """Product instance"""
    class Meta:
        managed = True

    name = models.CharField(max_length=255)
    price = models.FloatField()
    description = models.TextField()
    image = models.ImageField(upload_to='products_imgs/')

    def __str__(self):
        return self.name


class Invoice(models.Model):
    """Invoice instance"""
    class Meta:
        managed = True

    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    invoice_date = models.DateField(auto_now_add=True)
    sell_date = models.DateField()
    invoice_number = models.CharField(max_length=255, default=f'FV/{datetime.datetime.now().day}/{datetime.datetime.now().month}/{datetime.datetime.now().year}')
    seller = models.CharField(max_length=255, default='Magazine')
    total_net = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_brutto = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    payment_method = models.CharField(max_length=255, default="Web transfer")
    payment_date = models.DateField()

    def __str__(self):
        return self.invoice_number


class InvoicePosition(models.Model):
    """Invoice Product with amount position (one product row)"""
    class Meta:
        managed = True

    invoice = models.ForeignKey(Invoice, on_delete=models.PROTECT)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    amount = models.DecimalField(max_digits=6, decimal_places=0, default=1, validators=[MinValueValidator(Decimal('1'))])
    total_net = models.DecimalField(max_digits=20, decimal_places=2, default=0, validators=[MinValueValidator(Decimal('0.01'))])

    def __str__(self):
        return f'{self.product}, {self.amount} {"pc" if self.amount == 1 else "pcs"}'

templates/add_client.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>Add client to database</title>
    <link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC">
</head>
<body>
    <h1>Add client to database</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add client</button>
    </form>
{#    <form action="/register_client/" method="post">#}
{#        <label for="first_name">First name:</label>#}
{#        <input type="text" name="first_name" id="first_name" required>#}
{#        <label for="last_name">Last name:</label>#}
{#        <input type="text" name="last_name" id="last_name" required>#}
{#        <label for="email">Email:</label>#}
{#        <input type="email" name="email" id="email" required>#}
{#        <label for="phone">Phone:</label>#}
{#        <input type="tel" name="phone" id="phone" pattern="[0-9]{3}[0-9]{3}[0-9]{3}" required>#}
{#        <label for="address">Address:</label>#}
{#        <input type="text" name="address" id="address" required>#}
{#        <label for="city">City:</label>#}
{#        <input type="text" name="city" id="city" required>#}
{#        <label for="country">Country:</label>#}
{#        <input type="text" name="country" id="country" required>#}
{#        <label for="post-code">Post code:</label>#}
{#        <input type="text" name="post-code" id="post-code" required>#}
{#        <label for="nip">NIP:</label>#}
{#        <input type="text" name="nip" id="nip">#}
{#        <input type="submit" value="Add client">#}
{#    </form>#}
    <a href="http://127.0.0.1:8000/">Homepage</a>
</body>
</html>

templates/add_invoice.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>Add invoice to database</title>
    <link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC">
</head>
<body>
    <h1>Add invoice to database</h1>
    <form id="form-container" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ invoiceform.as_p }}
        {{ formset.management_form }}

        {% for form in formset %}
            <div class="product-form" style="border: 2px solid black;">
            {{ form.as_p }}
            </div>
        {% endfor %}
        <br>
        <button id="add-form" type="button">Add another product</button>
        <button id="remove-form" type="button">Remove last product</button>
        <br>
        <br>
        <br>
        <button type="submit" class="btn btn-block btn-primary">Add invoice</button>
    </form>
    <br>
    <br>
    <br>
    <a href="http://127.0.0.1:8000/">Homepage</a>

    <script>
        let productForm = document.querySelectorAll(".product-form")
        let container = document.querySelector("#form-container")
        let addButton = document.querySelector("#add-form")
        let removeButton = document.querySelector("#remove-form")
        let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
        let formNum = productForm.length-1

        addButton.addEventListener('click', addForm)
        removeButton.addEventListener('click', removeForm)

        function addForm(e){
            e.preventDefault()

            let newForm = productForm[0].cloneNode(true)
            const formRegex = RegExp(`form-(\\d){1}-`,'g')

            formNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
            container.insertBefore(newForm, addButton)

            totalForms.setAttribute('value', `${formNum+1}`)
        }

        function removeForm(e){
            e.preventDefault()
            const productForm = document.querySelectorAll(".product-form")
            if (formNum !== 0) {
                const lastForm = productForm[formNum]
                lastForm.remove()
                formNum--
                totalForms.setAttribute('value', `${formNum+1}`)
            }
        }
    </script>
    <script>
        const total_net = document.querySelector('#id_total_net')
        const total_brutto = document.querySelector('#id_total_brutto')
        document.addEventListener('change', updateTotal)
        total_net.addEventListener('change', updateBrutto)

        function updateTotal() {
            const prodForm = document.querySelectorAll(".product-form")
            let total = 0
            prodForm.forEach(function (element, index, array) {
                console.log(element.lastElementChild.children[1])
                const product_net = parseInt(element.lastElementChild.children[1].value)
                total += product_net
            })
            total_net.value = total
            updateBrutto()
        }

        function updateBrutto() {
            total_brutto.value = total_net.value*1.23.toFixed(2)
        }
    </script>
</body>

templates/add_product.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>Add product to database</title>
    <link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC">
</head>
<body>
    <h1>Add product to database</h1>
{#    <form action="/register_product/" method="post">#}
{#        <label for="product_name">#}
{#            Product name:#}
{#            <input type="text" name="product_name" id="product_name" required>#}
{#        </label>#}
{#        <label for="product_description">#}
{#            Description:#}
{#            <textarea name="product_description" cols="40" rows="5" required></textarea>#}
{#        </label>#}
{#        <label for="product_price">#}
{#            Price ($)#}
{#            <input type="number" name="product_price" id="product_price" required>#}
{#        </label>#}
{#        <label>#}
{#            Product image:#}
{#            <input type="file" name="product_image" id="product_image">#}
{#        </label>#}
{##}
{#        <input type="submit" value="Add product">#}
{#    </form>#}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add product</button>
    </form>
    <a href="http://127.0.0.1:8000/">Homepage</a>
</body>

templates/alert.html
<!DOCTYPE HTML>
<head>
    <title>Error</title>
</head>
<body>
    <script>
        alert('{{ message }}');
    </script>
</body>

templates/homepage.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Homepage</title>
    <link rel="icon"
          href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC">
</head>
<body>
    <h1>You're at the panel homepage.</h1>
    <a href="/add_client/">Add new client</a>
    <br>
    <a href="/add_product/">Add new product</a>
    <br>
    <a href="/add_invoice/">Add new invoice</a>
</body>
</html>

templates/success.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
    <link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC">
</head>
<body>
    <h1>Action performed successfully</h1>
    <a href="http://127.0.0.1:8000/">Homepage</a>
</body>
</html>